In [1]:
import os
import sys

# add the 'src' directory as one where we can import modules
# os.pardir refers to parent directory. 
# src_dir = os.path.join(os.getcwd(), '../src') => works the same
src_dir = os.path.join(os.getcwd(), os.pardir, 'src')
sys.path.append(src_dir)

# Load the "autoreload" extension
%load_ext autoreload
# always reload modules marked with "%aimport"
%autoreload 2

In [2]:
import numpy as np
array = np.asarray([[1,2],[3,4]])
print (array.shape)
print (array[:,1])

(2, 2)
[2 4]


In [3]:
from bs4 import BeautifulSoup

# 2. Data exploration - Understand each column by recording observations and characteristics of each column.

In [6]:
import pandas as pd
import matplotlib as plot

In [42]:
import gzip


# takes in csv and return data in list of list
def read_data(file_dir):
    data = []
    with gzip.open(file_dir, 'rb') as f:
        for line in f:
            data.append(line.decode('utf-8').split(','))
    f.close()
    return data

In [43]:
data = read_data('../data/train/data_train.csv.gz')
print (len(data))

36283


In [44]:
header = ['country','sku_id','title','category_lvl_1','category_lvl_2','category_lvl_3','short_description', 'price','product_type']
df = No`ne
with gzip.open('../data/train/data_train.csv.gz', 'r') as f:
    df = pd.read_csv(f, encoding='utf8', names=header)
df.shape

(36283, 9)

# 3. Data cleansing - Can be done simultaneously with step one. Removing duplicates, incorrect data and interpolate blank fields when needed.

# 5. Modeling - Features engineering, model evaluation using gridsearch.

# Experiment 1 - Using description only

In [75]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --y_train ../data/train/clarity_train.labels --pp True --model nb --feat tf --results ../results/clarity_1.txt



x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
pp True
model nb
feat tf
results ../results/clarity_1.txt


/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)


confusion matrix:

[[ 104  471]
 [ 387 9923]]


binary f1: 0.958558732612

rmse: 0.2631



In [77]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --y_train ../data/train/clarity_train.labels --pp True --model nb --feat tf --results ../results/clarity_1.txt




x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
pp True
model nb
feat tf
results ../results/clarity_1.txt


/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)


confusion matrix:

[[ 107  512]
 [ 367 9899]]


binary f1: 0.957488997437

rmse: 0.2666



# Experiment 2

In [81]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --y_train ../data/train/clarity_train.labels --pp False --model nb --feat tfidf --results ../results/clarity_2.txt



x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
pp True
model nb
feat tfidf
results ../results/clarity_2.txt


/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)


confusion matrix:

[[    1   609]
 [    3 10272]]


binary f1: 0.971072036302

rmse: 0.2332



# Experiment 3

In [84]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --y_train ../data/train/clarity_train.labels --pp True --model nb --feat tfidf --results ../results/clarity_3.txt




x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
pp True
model nb
feat tfidf
results ../results/clarity_3.txt


/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)
/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'//'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)


confusion matrix:

[[    3   602]
 [    4 10276]]


binary f1: 0.971358351451

rmse: 0.2316



In [98]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --x_test ../data/validate/data_valid.csv.gz --y_train ../data/train/clarity_train.labels --pp False --model nb --feat tfidf --results ../results/clarity_4.txt


x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
x_test ../data/validate/data_valid.csv.gz
pp True
model nb
feat tfidf
results ../results/clarity_4.txt


/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)
/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'//'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)


confusion matrix:

[[    0   602]
 [    4 10279]]


binary f1: 0.971366471366

rmse: 0.2307



/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)


# Experiment 4 - Using product title only

In [100]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --x_test ../data/validate/data_valid.csv.gz --y_train ../data/train/clarity_train.labels --pp False --model nb --feat tfidf --results ../results/clarity_5.txt


x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
x_test ../data/validate/data_valid.csv.gz
pp True
model nb
feat tfidf
results ../results/clarity_5.txt
confusion matrix:

[[    0   624]
 [    0 10261]]


binary f1: 0.970490872978

rmse: 0.2319



In [103]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --x_test ../data/validate/data_valid.csv.gz --y_train ../data/train/clarity_train.labels --pp False --model nb --feat tfidf --results ../results/clarity_5.txt



x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
x_test ../data/validate/data_valid.csv.gz
pp True
model nb
feat tfidf
results ../results/clarity_5.txt
confusion matrix:

[[    1   629]
 [    0 10255]]


binary f1: 0.970244571645

rmse: 0.2324



In [107]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --x_test ../data/validate/data_valid.csv.gz --y_train ../data/train/clarity_train.labels --pp False --model lr --feat tfidf --results ../results/clarity_6.txt



x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
x_test ../data/validate/data_valid.csv.gz
pp True
model lr
feat tfidf
results ../results/clarity_6.txt
confusion matrix:

[[   32   564]
 [   21 10268]]


binary f1: 0.972302447801

rmse: 0.2113



In [113]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --x_test ../data/validate/data_valid.csv.gz --y_train ../data/train/clarity_train.labels --pp False --model lr --feat tfidf --results ../results/clarity_7.txt


x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
x_test ../data/validate/data_valid.csv.gz
pp True
model lr
feat tfidf
results ../results/clarity_7.txt


/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)
/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'//'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)


confusion matrix:

[[    0   618]
 [    2 10265]]


binary f1: 0.970685579196

rmse: 0.2230



/Users/changsheng/anaconda/lib/python3.6/site-packages/bs4/__init__.py:219: UserWarning: "b'.'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)


In [114]:
%run ../src/models/clarity_train.py --x_train ../data/train/data_train.csv.gz --x_test ../data/test/data_test.csv.gz --y_train ../data/train/clarity_train.labels --pp False --model lr --feat tfidf --results ../results/clarity_7.txt


x_train ../data/train/data_train.csv.gz
y_train ../data/train/clarity_train.labels
x_test ../data/test/data_test.csv.gz
pp True
model lr
feat tfidf
results ../results/clarity_7.txt
confusion matrix:

[[   13   604]
 [   24 10244]]


binary f1: 0.970259518848

rmse: 0.2179

